osx_image: xcode8.2
language: objective-c
cache:
  - bundler
  - cocoapods
podfile: Example/Podfile
before_install:
  - gem update --system
  - gem --version
  - xcrun simctl delete 22FA2149-1241-469C-BF6D-462D3837DB72 || echo "remove workaround to delete duplicate simulator, see https://github.com/travis-ci/travis-ci/issues/7031#issuecomment-268317546"
before_script:
  - gem install bundler
  - gem install xcpretty
  - bundle
script:
  - bundle exec pod --version
  - bundle exec pod lib lint
  - set -o pipefail && xcodebuild -workspace Example/KIF-Quick.xcworkspace -scheme KIF-Quick-Example -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.2' ONLY_ACTIVE_ARCH=NO test | xcpretty
